---
# Nikolay - Edit the tool shed 

# Check which variables are inśtantiated
- debug:
    var: galaxy_config_dir
- debug:
    msg: "Galaxy server directory is {{ lookup('vars', 'galaxy_server_dir') }}"

- name: Insert New BLock in tool_shed
  lineinfile:
    path: "{{ galaxy_server_dir }}/config/tool_sheds_conf.xml.sample"
    backup: yes
    insertbefore: '^</tool_sheds>'
    line: '      <tool_shed name="NELS Tool Shed" url="https://galaxy-ntnu.bioinfo.no/toolshed_nels/"/>'
      
  remote_user: "{{ galaxy_remote_users.galaxy | default(omit) }}"
  become: "{{ true if galaxy_become_users.galaxy is defined else __galaxy_become }}"
  become_user: "{{ galaxy_become_users.galaxy | default(ansible_user_id) }}"
